### ISSUE TITLE
c0up issue

### ISSUE THREAD

**Issue by rowbot1** [PabloMansanet/c0toolkit#1]
Hi, I seem to have an issue when I'm running c0up

[root:/opt/c0toolkit]# export PATH=$PATH:/usr/bin/impacket-smbserver                                                                                                 (master) 
[root:/opt/c0toolkit]# echo $PATH                                                                                                                                    (master) 
:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/impacket-smbserver
[root:/opt/c0toolkit]# cd -                                                                                                                                          (master) 
/opt
[root:/opt]# cd -
/opt/c0toolkit
[root:/opt/c0toolkit]# ./c0up -s README.md                                                                                                                           (master) 
The -s (--smb) option requires impacket-smbserver in your PATH
    * https://github.com/SecureAuthCorp/impacket

have i added smbserver correctly to path?

**Comment by rewardone** [comment]
There is a space in your path. Try:
export PATH=$PATH:/usr/bin/impacket-smbserver\ (master)
though that might be something special added to your terminal instead of the folder name..

or simply install the impacket tools using setup.py install. The setup will copy all of the impacket tools to your PATH for you. 

c0up determines if it's in your PATH by issuing: which impacket-smbserver
So you can test to see if you added it to your PATH successfully.

**Comment by rowbot1** [comment]
i tried all of the above but still getting an issue:

[root:/opt/impacket]# export PATH=/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/impacket-smbserver
[root:/opt/impacket]# echo $PATH                                                                                                                                     (master) 
/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/impacket-smbserver
[root:/opt/impacket]# cd ../c0toolkit                                                                                                                                (master) 
[root:/opt/c0toolkit]# ./c0up -s README.md                                                                                                                           (master) 
The -s (--smb) option requires impacket-smbserver in your PATH
    * https://github.com/SecureAuthCorp/impacket

**Comment by rewardone** [comment]
Provide a listing of your impacket-smbserver directory

**Comment by rowbot1** [comment]
[root:/opt/c0toolkit]# ls -la /usr/bin/impacket-smbserver                                                                                                            (master) 
lrwxrwxrwx 1 root root 24 Jun  6 14:00 /usr/bin/impacket-smbserver -> ../share/impacket/script
[root:/opt/c0toolkit]#

**Comment by rewardone** [comment]
ok....provide a listing of your ../share/impacket/script directory

**Comment by rowbot1** [comment]
[root:/opt/c0toolkit]# ls -la /usr/share/impacket/script                                                                                                             (master) 
-rwxr-xr-x 1 root root 152 Jun  6 14:00 /usr/share/impacket/script
[root:/opt/c0toolkit]#

**Comment by rewardone** [comment]
Please list the contents of the /usr/share/impacket/script directory.

**Comment by rowbot1** [comment]
there doesnt seem to be anything in there. I have ran pip install . for impacket as well with no errors.

[root:/opt/c0toolkit]# locate /share/impacket/script                                                                                                                 (master) 
/usr/share/impacket/script
[root:/opt/c0toolkit]# ls -la /usr/share/impacket/script                                                                                                             (master) 
-rwxr-xr-x 1 root root 152 Jun  6 14:00 /usr/share/impacket/script
[root:/opt/c0toolkit]# ls -la  /usr/share/impacket/script                                                                                                            (master) 
-rwxr-xr-x 1 root root 152 Jun  6 14:00 /usr/share/impacket/script
[root:/opt/c0toolkit]# cd /usr/share/impacket/                                                                                                                       (master) 
[root:/usr/share/impacket]# ls
script
[root:/usr/share/impacket]# ./script 
python: can't open file '/usr/share/doc/python-impacket/examples/script.py': [Errno 2] No such file or directory
[root:/usr/share/impacket]#

**Comment by rewardone** [comment]
If your directory is empty, it means you were not able to clone it successfully. 
git clone https://github.com/SecureAuthCorp/impacket.git && cd impacket && pip install .

**Comment by rowbot1** [comment]
are these the files you're looking for ?

root:/opt/impacket/impacket]# ls                                                                                                                                    (master) 
Dot11Crypto.py      IP6_Extension_Headers.py  cdp.py     dot11.py  helper.py          nmb.py             smb.py            spnego.py         version.py
Dot11KeyManager.py  ImpactDecoder.py          crypto.py  dpapi.py  hresult_errors.py  nt_errors.py       smb3.py           structure.py      winregistry.py
ICMP6.py            ImpactPacket.py           dcerpc     eap.py    krb5               ntlm.py            smb3structs.py    system_errors.py  wps.py
IP6.py              NDP.py                    dhcp.py    ese.py    ldap               pcap_linktypes.py  smbconnection.py  tds.py
IP6_Address.py      __init__.py               dns.py     examples  mqtt.py            pcapfile.py        smbserver.py      uuid.py
[root:/opt/impacket/impacket]#

**Comment by PabloMansanet** [comment]
@rowbot1 That's because the newer impacket (the one that doesn't come bundled with the PWK image) is called differently. You'll have to modify the c0up script to call "python smbserver.py" instead of "impacket-smbserver" :)

Alternatively, you can create your on shell script called impacket-smbserver that just calls the python version passing all arguments to it.

**Comment by rowbot1** [comment]
ok great thank you

**Comment by PabloMansanet** [comment]
Closing then!
